2024-11-06 21:02:14,935 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "e:\Urban\rep\Urban-University-Homework\module_12\tests_12_4.py", line 75, in test_run
    runner = Runner(2)
  File "e:\Urban\rep\Urban-University-Homework\module_12\tests_12_4.py", line 11, in __init__
    raise TypeError(
TypeError: Имя может быть только строкой, передано int
2024-11-06 21:02:14,935 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "e:\Urban\rep\Urban-University-Homework\module_12\tests_12_4.py", line 64, in test_walk
    runner = Runner('Maria', -5)
  File "e:\Urban\rep\Urban-University-Homework\module_12\tests_12_4.py", line 17, in __init__
    raise ValueError(
ValueError: Скорость не может быть отрицательной, сейчас -5
